// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Handle_OSX_Window_HeaderFile
#define _Handle_OSX_Window_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_Aspect_Window_HeaderFile
#include <Handle_Aspect_Window.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(Aspect_Window);
class OSX_Window;


DEFINE_STANDARD_HANDLE(OSX_Window, Aspect_Window)

/*
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(OSX_Window);

class Handle(OSX_Window) : public Handle(Aspect_Window) {
  public:
    Handle(OSX_Window)():Handle(Aspect_Window)() {} 
    Handle(OSX_Window)(const Handle(OSX_Window)& aHandle) : Handle(Aspect_Window)(aHandle) { }

    Handle(OSX_Window)(const OSX_Window* anItem) : Handle(Aspect_Window)((Aspect_Window *)anItem) { }

    Handle(OSX_Window)& operator=(const Handle(OSX_Window)& aHandle) {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(OSX_Window)& operator=(const OSX_Window* anItem) {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    OSX_Window* operator->() const {
      return (OSX_Window *)ControlAccess();
     }

//   Standard_EXPORT ~Handle(Xw_Window)();
 
   Standard_EXPORT static const Handle(OSX_Window) DownCast(const Handle(Standard_Transient)& AnObject);
};
*/
#endif
